name: custom_radio_grouped_button
description: Custom Radio Buttons and Grouped Check Box Button
version: 2.2.0

homepage: https://github.com/miyabi1224/custom_radio_grouped_button_myabeee

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
